config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :new
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash[:notice] = "You have created book successfully."
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
    @book = Book.new
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      @book = Book.new
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if (@new_book || @book).errors.any? %>
  <%= (@new_book || @book).errors.count %>error prohibited this obj from being saved:
  <ul>
    <% (@new_book || @book).errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<p id="notice"></p>
<h2>User info</h2>
<% if @user&.profile_image.attached? %>
  <%= image_tag @user.get_profile_image(100,100) %>
<% else %>
  <%= image_tag 'no-image', size: "100x100" %>
<% end %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <td><%= @user&.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= @user&.introduction %></td>
    </tr>
    </tbody>
</table>
  <% if @user == current_user %>
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
<div class="row">
  <% if @user && @user != current_user %>
    <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: (@new_book || @book), url: books_path, method: :post, local: true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title w-100" %>
  </div>
  <div class="form-group">
    <label for="book_body">Body</label>
    <%= f.text_area :body, class: "form-control book_body w-100" %>
  </div>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <p id="notice"></p>
      <h2>User info</h2>
      <% if @user&.profile_image.attached? %>
        <%= image_tag @user.get_profile_image(100,100) %>
      <% else %>
        <%= image_tag 'no-image', size: "100x100" %>
      <% end %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <td><%= @user&.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user&.introduction %></td>
          </tr>
          </tbody>
      </table>
      <% if @user == current_user %>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Editing Book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
    <div>
      <h4>Title</h4>
      <%= f.text_field :title %>
    </div>
    <div>
      <h4>Body</h4>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Update Book' %>
  <% end %>
  
  <%= link_to "Show", book_path(@book.id) %> |
  <%= link_to "Back", books_path %>
</div> 

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Books</h2>
      <div class="table-responsive">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.get_profile_image(50, 50), class: "img-fluid" %>
                  <% else %>
                    <%= image_tag 'no-image', size: "50x50", class: "img-fluid" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book), class: "text-primary" %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Books</h2>
      <div class="table-responsive">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if book.user.profile_image.attached? %>
                  <%= image_tag book.user.get_profile_image(50, 50), class: "img-fluid" %>
                <% else %>
                  <%= image_tag 'no-image', size: "50x50", class: "img-fluid" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book), class: "text-primary" %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Book detail</h2>
      <table class="table table-hover align-middle">
        <tbody>
          <tr>
            <td>
          <%= link_to user_path(@book.user) do %>
            <% if @book.user.profile_image.attached? %>
              <%= image_tag @book.user.profile_image.variant(resize_to_limit: [80, 80]) %>
            <% else %>
              <%= image_tag 'no-image.jpg', size: '80x80' %>
            <% end %>
            <%= @book.user.name %>
          <% end %>
         </td>
         <td><%= link_to @book.title, book_path(@book.id) %></td>
         <td><%= @book.body %></td>
         <% if @book.user == current_user %>
         <td>
           <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-sm btn-success' %>
         </td>
         <td>
           <%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-danger' %>
         </td>
         <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/about.html.erb
<h1>Welcome to the Bookers!</h1>
<i class="fas fa-book"></i>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/6913a12862.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

        <h1>welcome to the <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
       <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
       </div>
     </div>
    </div>
  </div>
</header>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/6913a12862.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                   <%= link_to raw('<i class="fa-solid fa-home"></i> Home'), user_path(current_user), class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-users"></i> Users'), users_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-book-open"></i> Books'), books_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-sign-out-alt"></i> Log out'), destroy_user_session_path, method: :delete, class: 'nav-link text-light', data: { confirm: 'Are you sure?' } %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-home"></i> Home'), root_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-link"></i> About'), '/home/about', class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-user-plus"></i> Sign up'), new_user_registration_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-sign-in-alt"></i> Log in'), new_user_session_path, class: "nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main class="m">
      <%= flash[:notice] %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_list.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<p id="notice"></p>
<h2>User info</h2>
    <% if @user.profile_image.attached? %>
      <%= image_tag @user.get_profile_image(100,100) %>
    <% else %>
      <%= image_tag 'no-image', size: "100x100" %>
    <% end %>
    <table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= @user.introduction %></td>
    </tr>
    </tbody>
  </table>
    <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book, url: books_path, method: :post, local: true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title w-100" %>
      </div>
      <div class="form-group">
        <label for="book_body">Body</label>
        <%= f.text_area :body, class: "form-control book_body w-100" %>
      </div>
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <p id="notice"></p>
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user, url: user_path(@user.id), method: :patch, local: true do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label>Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Users</h2>
      <div class="table-responsive">
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
           <td>
            <% if user.profile_image.attached? %>
              <%= image_tag user.get_profile_image(50,50) %>
            <% else %>
              <%= image_tag 'no-image', size: "50x50" %>
            <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
     </table>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <p id="notice"></p>
      <h2>Books</h2>
      <div class="table-responsive">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
          </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
           <td>
            <%= link_to user_path(book.user) do %>
              <% if book.user.profile_image.attached? %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% else %>
                <%= image_tag 'no-image', size: "50x50" %>
              <% end %>
            <% end %>
           </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
        </table>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>